services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: port-narawit-web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always

  web-dev:
    image: node:20-alpine
    container_name: port-narawit-web-dev
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - PORT=3000
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # Useful for Hot Module Replacement in Docker containers on Windows
    command: npm run dev
